name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: GoGet
      run: go get github.com/bitly/go-simplejson && go get github.com/ebfe/keccak && go get github.com/jzelinskie/whirlpool && go get github.com/satori/go.uuid && go get github.com/gorilla/websocket && go get github.com/valyala/fastjson && go get github.com/BurntSushi/toml && go get github.com/atwat/bigoo

    - name: Run
      env:
        toml: ${{secrets.toml}}
      run: go build && ./bigoo --toml=${toml}

